name: Publish Frontend Docker

on:
  release:
    types: [published]

jobs:
  push_to_registry:
    name: Push frontend image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Github Registry
        env:
          GITHUB_USER: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: $GITHUB_USER
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        env:
          REGISTRY: ghcr.io
          OWNER: tradingstrategy-ai
          IMAGE_NAME: ${{ github.repository }}
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          target: final
          push: true
          tags: |
            $REGISTRY/$OWNER/$IMAGE_NAME:$(date +%s)
          build-args: |
            ENVIRONMENT=production
