name: Automated test suite

on:
  push:
    branches: 
      - master
    tags:
      - 'v*'
  pull_request: # we can use docker image in PR for testing
    branches: 
      - master

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: 'npm'
          cache-dependency-path: |
            package-lock.json
            theme/package-lock.json
      - name: Install dependencies
        run: npm install
      # - name: Package version check
      #   run: npm ls
      - name: Run Cypress
        run: bash run-cypress.bash

  build:
    runs-on: ubuntu-latest
    needs: test
    # Skip build on master push
    if: ${{ !(github.event_name == 'push' && github.ref == 'master') }}
    env:
      REGISTRY: ghcr.io
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1     
      - name: Read metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}
      - name: Log in to Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          # experimental: https://github.com/docker/build-push-action/blob/master/docs/advanced/cache.md#cache-backend-api
          cache-from: type=gha
          cache-to: type=gha,mode=max
