name: Automated test suite

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
          npm install
    - name: Package version check
      run: |
          npm ls
    - name: Checkout submodules
      run: git submodule set-url theme https://github.com/tradingstrategy-ai/theme.git && git submodule update --init --recursive
    - name: Run Cypress
      run: |
        bash run-cypress.bash
      env:
        VITE_PUBLIC_BACKEND_URL: https://tradingstrategy.ai/api
        VITE_PUBLIC_GHOST_API_URL: ${{ env.VITE_PUBLIC_GHOST_API_URL }}
        VITE_PUBLIC_GHOST_CONTENT_API_KEY : ${{ env.VITE_PUBLIC_GHOST_CONTENT_API_KEY }}
    - name: Package for server-side rendering using SvelteKit Node.js adapter
      run: |
        npm run ssr:node
      env:
        VITE_PUBLIC_BACKEND_URL: https://tradingstrategy.ai/api
        VITE_PUBLIC_GHOST_API_URL: ${{ env.VITE_PUBLIC_GHOST_API_URL }}
        VITE_PUBLIC_GHOST_CONTENT_API_KEY : ${{ env.VITE_PUBLIC_GHOST_CONTENT_API_KEY }}
        PRODUCTION: true

