name: Cypress integration tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  cypress:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.15
          registry-url: https://npm.pkg.github.com/
      - name: Use SSH deploy key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Install dependencies
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}
        run: npm ci
      - name: Package version check
        run: npm ls
      - name: Code format check
        run: npm run format:check
      - name: Checkout submodules
        run: git submodule set-url theme https://github.com/tradingstrategy-ai/theme.git
      - name: Setup submodules
        run: bash scripts/build-deps.sh
      - name: Run Cypress
        run: bash scripts/run-cypress.bash
        env:
          VITE_PUBLIC_GHOST_API_URL: ${{ secrets.VITE_PUBLIC_GHOST_API_URL }}
          VITE_PUBLIC_GHOST_CONTENT_API_KEY: ${{ secrets.VITE_PUBLIC_GHOST_CONTENT_API_KEY }}
          CYPRESS_KEY: ${{ secrets.CYPRESS_KEY }}
      - name: Package for server-side rendering using SvelteKit Node.js adapter
        run: npm run ssr:node
        env:
          VITE_PUBLIC_GHOST_API_URL: ${{ secrets.VITE_PUBLIC_GHOST_API_URL }}
          VITE_PUBLIC_GHOST_CONTENT_API_KEY: ${{ secrets.VITE_PUBLIC_GHOST_CONTENT_API_KEY }}
          PRODUCTION: true
